export const Quotes = [
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Believe you can and you're halfway there.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Your time is limited, don't waste it living someone else's life.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Don't watch the clock; do what it does. Keep going.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
    "The only way to do great work is to love what you do.",
    "The future starts today, not tomorrow.",
    "Dream big and dare to fail.",
    "Don't be afraid to give up the good to go for the great.",
    "Don't let yesterday take up too much of today.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are never too old to set another goal or to dream a new dream.",
    "If you can dream it, you can achieve it.",
    "Success is not in what you have, but who you are.",
    "The secret of getting ahead is getting started.",
    "Believe in yourself, and the rest will fall into place.",
    "The only person you are destined to become is the person you decide to be.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The harder I work, the luckier I get.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "You miss 100% of the shots you don't take.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Your time is limited, don't waste it living someone else's life.",
    "It always seems impossible until it's done.",
    "Believe you can and you're halfway there.",
    "Don't watch the clock; do what it does. Keep going.",
    "Aim for the moon. If you miss, you may hit a star.",
    "The only way to do great work is to love what you do.",
    "The future starts today, not tomorrow.",
    "Dream big and dare to fail.",
    "Don't be afraid to give up the good to go for the great.",
    "Don't let yesterday take up too much of today.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are never too old to set another goal or to dream a new dream.",
    "If you can dream it, you can achieve it.",
    "Success is not in what you have, but who you are.",
    "The secret of getting ahead is getting started.",
    "Believe in yourself, and the rest will fall into place.",
    "The only person you are destined to become is the person you decide to be.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The harder I work, the luckier I get.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "You miss 100% of the shots you don't take.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Your time is limited, don't waste it living someone else's life.",
    "It always seems impossible until it's done.",
    "Believe you can and you're halfway there.",
    "Don't watch the clock; do what it does. Keep going.",
    "Aim for the moon. If you miss, you may hit a star.",
    "The only way to do great work is to love what you do.",
    "The future starts today, not tomorrow.",
    "Dream big and dare to fail.",
    "Don't be afraid to give up the good to go for the great.",
    "Don't let yesterday take up too much of today.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "You are never too old to set another goal or to dream a new dream.",
    "If you can dream it, you can achieve it.",
    "Success is not in what you have, but who you are.",
    "The secret of getting ahead is getting started.",
    "Believe in yourself, and the rest will fall into place.",
    "The only person you are destined to become is the person you decide to be.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The harder I work, the luckier I get.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "You miss 100% of the shots you don't take."
];