export const CuriosQuotes = [
    "The important thing is not to stop questioning. Curiosity has its own reason for existing.",
    "The cure for boredom is curiosity. There is no cure for curiosity.",
    "Be curious, not judgmental.",
    "The world is full of magical things patiently waiting for our wits to grow sharper.",
    "Curiosity is the engine of achievement.",
    "Stay curious, my friend.",
    "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.",
    "Curiosity is the spark behind the spark of every great idea.",
    "Curiosity is the wick in the candle of learning.",
    "Curiosity is the fuel for discovery, inquiry, and learning.",
    "The first and simplest emotion which we discover in the human mind is curiosity.",
    "Curiosity is the key that unlocks the door to infinite possibilities.",
    "Curiosity is the compass that leads us to new worlds.",
    "Be curious, be adventurous, be bold. There's a whole world out there waiting to be explored.",
    "The cure for ignorance is curiosity.",
    "Curiosity is the secret ingredient to creativity.",
    "Curiosity is the bridge between the known and the unknown.",
    "Curiosity is the foundation of learning.",
    "Curiosity is the spark that ignites the fire of knowledge.",
    "The curious mind is never bored.",
    "Curiosity is the driving force behind progress.",
    "Stay curious, keep learning.",
    "Curiosity is the key that unlocks the door to understanding.",
    "The curious ones are always the ones who discover the extraordinary.",
    "Curiosity is the compass that guides us through the unknown.",
    "Embrace your curiosity, for it will lead you to amazing places.",
    "Curiosity is the seed of knowledge that grows into wisdom.",
    "Curiosity is the pathway to new experiences.",
    "The curious mind explores the world with wonder.",
    "Curiosity is the key to unlocking the mysteries of life.",
    "Stay curious, for there is always more to learn.",
    "Curiosity is the beginning of wisdom.",
    "The curious mind never stops seeking knowledge.",
    "Curiosity is the gateway to new discoveries.",
    "Curiosity is the fuel that drives innovation.",
    "The curious ones are the ones who change the world.",
    "Curiosity is the elixir of growth and self-discovery.",
    "The curious mind is an insatiable learner.",
    "Curiosity opens the door to endless possibilities.",
    "The curious mind is a wandering mind, always seeking new horizons.",
    "Curiosity is the compass that points us towards knowledge.",
    "The curious ones are the ones who find the answers.",
    "Curiosity is the wind beneath the wings of imagination.",
    "Stay curious, and the world will unfold its secrets to you.",
    "Curiosity is the thirst for knowledge that can never be quenched.",
    "The curious mind is a treasure chest of ideas.",
    "Curiosity is the key that unlocks the door to enlightenment.",
    "Stay curious, for the world is a fascinating place.",
    "Curiosity is the compass that guides us on the path of discovery.",
    "The curious mind sees the world through a lens of wonder.",
    "Curiosity is the driving force behind personal growth.",
    "Stay curious, and you'll always find something new to explore."
]